# Generated by Django 3.0.8 on 2020-07-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cad_Condomino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_apto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_despesa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item_Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_item_despesa', models.CharField(max_length=100)),
                ('tipo_despesa', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.Tipo_Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Desp_Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdade_gas', models.FloatField(max_length=8)),
                ('mes_ref', models.DateField()),
                ('item_despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='despesas.Item_Despesas')),
                ('num_apto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='despesas.Cad_Condomino')),
            ],
        ),
        migrations.CreateModel(
            name='Desp_Comum_Parcelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('num_parc_comum', models.IntegerField(verbose_name='num_par_comum')),
                ('Valor_parc_comum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor_Parcela')),
                ('data_parc_comum', models.DateField(blank=True, null=True)),
                ('item_despesa', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.Item_Despesas')),
            ],
        ),
        migrations.CreateModel(
            name='Desp_Comum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_desp_comum', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor')),
                ('data_desp_comum', models.DateField(blank=True, null=True)),
                ('item_despesa', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesas.Item_Despesas')),
            ],
        ),
    ]
